// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDylL0epX7sw528Yp0EuDiKf4_rQKsAyT0',
    appId: '1:259061766735:web:8d30fa885b6d97b91fe83a',
    messagingSenderId: '259061766735',
    projectId: 'flutter-news-app-c3502',
    authDomain: 'flutter-news-app-c3502.firebaseapp.com',
    storageBucket: 'flutter-news-app-c3502.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1UvTW7vCa9AIhRS9mOXt3N2AuRnygvTM',
    appId: '1:259061766735:android:8d7580f5192365171fe83a',
    messagingSenderId: '259061766735',
    projectId: 'flutter-news-app-c3502',
    storageBucket: 'flutter-news-app-c3502.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYYqPsc77OJwwYbfEv76A0hpKLnE5GLKY',
    appId: '1:259061766735:ios:3963ce08a399d56b1fe83a',
    messagingSenderId: '259061766735',
    projectId: 'flutter-news-app-c3502',
    storageBucket: 'flutter-news-app-c3502.appspot.com',
    iosBundleId: 'com.example.flutterNewsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYYqPsc77OJwwYbfEv76A0hpKLnE5GLKY',
    appId: '1:259061766735:ios:ff0d0efd0555553d1fe83a',
    messagingSenderId: '259061766735',
    projectId: 'flutter-news-app-c3502',
    storageBucket: 'flutter-news-app-c3502.appspot.com',
    iosBundleId: 'com.example.flutterNewsApp.RunnerTests',
  );
}
